### PR TITLE
Ensure that `_nanmean_mapreduce!` inserts nans for zero counts

### LINKED ISSUE #59: Bug with nanmean
I am using NaNStatistics v0.6.52 and encountered a bug with `nanmean`. See the minimal working example below.

```julia
using NaNStatistics
using Test

# Expected
small_data = fill(NaN, 2, 3, 4)
nan_mean_small_data = nanmean(small_data, dims = 2)
@test isequal(nan_mean_small_data, fill(NaN, 2, 1, 4)) # pass

# Not expected
large_data = fill(NaN, 180, 10, 360)
nan_mean_large_data = nanmean(large_data, dims = 2)
@test isequal(nan_mean_large_data, fill(NaN, 180, 1, 360)) # fail
```

The values in `nan_mean_large_data` are all zeros instead of `NaN`s.

### PR DESCRIPTION
**Pull request by JamesWrigley**
Also added some more tests for `nansum`. In doing so I noticed that `nansum` will always give 0 instead of nan, which always annoyed me in numpy :stuck_out_tongue: Maybe we could change that in a later version? It'd be breaking though, and if people expect that behaviour then we'd need a way to opt in/out.

Fixes #59.

### CODE REVIEW

**Comment by brenhinkeller** [comment]
Ah yeah, `nansum` returning zeros for all-nan arrays was intentional, as an extension of the analogy between counting and summing (and I guess it's nice that it matches numpy), but if there's strong demand we could consider changing it or adding a kwarg to select

File: src/ArrayStats/nanmean.jl [hunk 1]
```diff
@@ -124,10 +124,10 @@ function _nanmean_mapreduce_impl!(B, A, counts)
...
 
-    ∅ = zero(eltype(B))
+    nan_value = convert(eltype(B), NaN)
     @inbounds for i in eachindex(B)
         if iszero(counts[i])
-            B[i] = ∅
+            B[i] = nan_value
         else
             B[i] /= counts[i]
         end
```
Comment (brenhinkeller) [inline src/ArrayStats/nanmean.jl:133]: This can be a problem for later, but I think you can probably avoid the branch entirely and just still use `            B[i] /= counts[i]` since `0/0` is `NaN`

Comment (JamesWrigley) [reply src/ArrayStats/nanmean.jl:133]: Ah cool, I didn't realize that.
